name: Build, Tag, and Push Docker Image

on:
  push:
    branches:
      - main
      - new_pipeline # ! for debug!!!

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Update patch version
        id: increment-patch-version
        run: ./gradlew incrementPatchVersion

      - name: Get version
        id: set-version
        run: |
          version=$(./gradlew getVersion --quiet | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          # Check if the version is empty
          if [ -z "$version" ]; then
            echo "Error: Version not found" >&2
            exit 1
          fi

          echo "Extracted version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "VERSION=$version" >> "$GITHUB_ENV"

      - name: Build jar
        run: ./gradlew build

      - name: Test jar
        run: |
          java -jar build/libs/gradle-hello-world-amit-${{ env.VERSION }}-all.jar

      - name: Upload updated gradle.properties artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-properties
          path: gradle.properties

      - name: Upload jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-hello-world-amit-jar
          path: build/libs/gradle-hello-world-amit-${{ env.VERSION }}-all.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get jar artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-hello-world-amit-jar
          path: build/libs/

      - name: check jar
        run: |
          ls -al
          ls -al build/libs

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:${{ env.VERSION }} .

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:latest

      - name: Download and run Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:${{ env.VERSION }}
          docker run -d --name gradle-hello-world ${{ secrets.DOCKER_USERNAME }}/gradle-hello-world:${{ env.VERSION }}

  commit-version:
    runs-on: ubuntu-latest
    needs: docker
    env:
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - name: Checkout repository for commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: true

      - name: Download updated gradle.properties artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-properties
          path: .

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated gradle.properties
        run: |
          # Add gradle.properties and check for changes
          git add gradle.properties
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update gradle.properties version to ${{ env.VERSION }} [skip ci]"
            git push
          else
            echo "No changes in gradle.properties to commit."
          fi
