name: Test of build, docker, and run

env:
  PROJECT_NAME: gradle-hello-world-amit

on:
  push:
    branches-ignore:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get version
        run: |
          version=$(./gradlew getVersion --quiet | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          # Check if the version is empty
          if [ -z "$version" ]; then
            echo "Error: Version not found" >&2
            exit 1
          fi

          echo "Extracted version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "VERSION=$version" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build --build-arg VERSION=${{ env.VERSION }} ${{ vars.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }} .
  
      - name: Test container
        run: docker run ${{ vars.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
